### ISSUE TITLE
Current prepair.js does not work binary2npm on linux

### ISSUE THREAD

**Issue by IanWorley** [dalisoft/typos-rs-npm#41]
Hey there I am currently trying to use this npm package. At this current time I am having issues with the prepair.js script in binary2npm. https://github.com/dalisoft/binary2npm/blob/988f2a441659c655a141b1beca2eca4b055ebe3a/prepare.js#L178C1-L186C1 . The issue I am getting must be related to this chuck of code. https://github.com/dalisoft/binary2npm/blob/988f2a441659c655a141b1beca2eca4b055ebe3a/prepare.js#L146C2-L178C1. It seems that the prepair.js can't determine what build to grab.

**Comment by dalisoft** [comment]
Hy @IanWorley 

Please specify your OS, Process, Arch and other useful informations so i could debug it. 

I will try fix it today, maximum by end of tomorrow. 

And thank you for using my small tool :)

**Comment by IanWorley** [comment]
No problem @dalisoft 

OS: Arch Linux x86_64
Kernel: Linux 6.6.63-1-lts
DE: KDE Plasma 6.2.3
WM: KWin (Wayland)
WM Theme: Breeze
Theme: Breeze (Dark) [Qt], Breeze-Dark [GTK2], Breeze [GTK3]
Icons: breeze-dark [Qt], breeze-dark [GTK2/3/4]
Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK2/3/4]
Cursor: breeze (24px)
Terminal: terminator 3.12.7
Terminal Font: Mono (10pt)
CPU: Intel(R) Core(TM) i7-9700K (8) @ 4.90 GHz
GPU: NVIDIA GeForce RTX 2070
Memory: 12.59 GiB / 15.54 GiB (81%)
Swap: 4.00 GiB / 4.00 GiB (100%)
Disk (/): 705.81 GiB / 914.83 GiB (77%) - ext4
Local IP (wlan0): 192.168.0.66/22
Locale: en_US.UTF-8

**Comment by dalisoft** [comment]
@IanWorley Thank you for your patience. Try remove lockfile, `node_modules` and cache and **re-install** last version. It should work on **Arch Linux**.
